(defun check-depth (s)
  (let ((depth 0)
        (max-depth 0)
        (len (length s))
        (i 0))
    (loop while (< i len)
          do (let ((c (char s i)))
               (cond
                 ((char= c #\() (incf depth) (when (> depth max-depth) (setf max-depth depth)))
                 ((char= c #\)) (decf depth))
                 ((char= c #\[) (incf depth))
                 ((char= c #\]) (decf depth))
                 ((char= c #\{) (incf depth))
                 ((char= c #\}) (decf depth))))
          (incf i))
    (values depth max-depth)))

;; Check specific lines from clojure-print-str
(let* ((line8050 "(get-output-stream-string s)))))")
       (line8051 "args)))))"))
  (format t "Line 8050: ~A~%" line8050)
  (multiple-value-bind (depth max) (check-depth line8050)
    (format t "  End depth: ~A, Max depth: ~A~%" depth max))
  (format t "Line 8051: ~A~%" line8051)
  (multiple-value-bind (depth max) (check-depth line8051)
    (format t "  End depth: ~A, Max depth: ~A~%" depth max)))
