(load "package.lisp")
(load "cl-clojure-syntax.lisp")
(load "cl-clojure-eval.lisp")

(in-package :cl-clojure-eval)

(cl-clojure-syntax:ensure-clojure-readtable)

(let ((*readtable* cl-clojure-syntax:*clojure-readtable*))
  (let ((code "(let [m {:a 1 :b 2}] (let [{:keys [:a :b]} m] [a b]))"))
    (format t "Code: ~a~%" code)
    (let ((form (cl-clojure-syntax:read-clojure-string code)))
      (format t "Form type: ~a~%" (type-of form))
      (format t "Form: ~a~%" form)
      (when (consp form)
        (format t "Form car: ~a~%" (car form))
        (format t "Form cadr: ~a~%" (cadr form))
        (format t "Form cadr type: ~a~%" (type-of (cadr form)))
        (when (vectorp (cadr form))
          (format t "Form cadr is vector, elements:~%")
          (loop for elem across (cadr form)
                do (format t "  elem=~a type=~a~%" elem (type-of elem))))))))
