(load "package.lisp")
(load "cl-clojure-syntax.lisp)
(in-package #:cl-clojure-syntax)
(enable-clojure-syntax)
(cl:let ((x (cl:read-from-string "{[{:keys [data]}] :via}")))
  (cl:format cl:t "Type: ~a~%" (cl:type-of x))
  (cl:maphash (cl:lambda (k v) (cl:format cl:t "Key type: ~a, Value type: ~a~%" (cl:type-of k) (cl:type-of v))) x)
  (cl:format cl:t "Keys: ~a~%" (cl:loop for k being the cl:hash-keys of x collect k))
  (cl:format cl:t "Values: ~a~%" (cl:loop for k being the cl:hash-keys of x collect (cl:gethash k x))))
